language: node_js
node_js:
  - "node"
script: scripts/build.sh
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_ACCESS_KEY_SECRET"
  bucket: "techradar.capgemini-psdu.com"
  skip_cleanup: true
  local_dir: dist
